### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by pzhwpz** [NLPWM-WHU/LSTPM#4]
首先感谢大佬提供了论文的代码，有几个问题想问一下：
1. 论文里面这个公式：
![image](https://user-images.githubusercontent.com/28777100/100348144-792d5480-3021-11eb-94f6-f3afb2e81abe.png)
左边的部分是不是指的softmax公式，如果是的话分子上是不是应该没有求和？
2. 公式里面的投影矩阵Wh和Wh'在代码里面都没有体现，不知道对结果是不是有影响？
3. train.py中130-133行我的个人理解是对于session中的每个item，生成的短期兴趣表示都是基于整个session的，这种训练方式会造成数据泄露，还希望作者能解释一下
4. 根据提供的数据跑了一下以后的结果并没有达到论文中的效果，运行下来的结果如下：

recall@1 | recall@5 | recall@10 | ndcg@1 | ndcg@5 | ndcg@10
-- | -- | -- | -- | -- | --
0.1453 | 0.3259 | 0.4017 | 0.1453 | 0.2401 | 0.2646

与论文相比还有一定的差距，是不是数据集与文中的有差异

**Comment by NLPWM-WHU** [comment]
你好，感谢你对这篇文章的关注！
1.这个公式中间的求和符号是对后面所有项目求和，包括W和s，因此是一个按权重加和的公式。
2.实现时，Wh‘是不需要的，这个是之前论文里面的小错误；同时，Wh是需要的。很抱歉误导了你。
3.这个是因为在训练过程中，训练数据都是已知的，因此短期兴趣的表示可以基于当前整个session来计算；在测试时候，会把session中未来的数据去除掉，所以is_train在测试时候设置为False。
4.我把代码更新了一下，可以跑出相近的效果；同时，如果你需要更好的效果，可以对每个用户引入一个用户向量并在最后一层参与预测，会得到更好的效果。
若还有问题，请单独联系我的邮箱：sunke1995@whu.edu.cn。

**Comment by pzhwpz** [comment]
好的，非常感谢~
