### ISSUE TITLE
Abnormal results if use data_process to generate cut_one_day.pkl

### ISSUE THREAD

**Issue by currybur** [NLPWM-WHU/LSTPM#5]
Hi, thank you so much for sharing your codes, it does help us a lot on our work!

But here is something strange while we evaluating on Gowalla dataset. The results appeared to be a lot higher than in your paper, that our recall@1, recall@5, recall@10 are 0.2901, 0.5619, 0.6529 respectively but  0.0984, 0.2021 0.2510 in your paper.

We have noticed that `data_process` is specified on Foursquare, but there seems to be little difference between the use of foursquare and gowalla so we modify several places in reading data file part and then the code runs well. Also we change some threshold parameters to reduce the number of users and locations to match the numbers in your paper. 

We also evaluated on foursquare, first we used provided `foursquare_cut_one_day.pkl` and the results were consistent with your paper. But then we generated `foursquare_cut_one_day.pkl` from original foursquare by `data_process.py`, and the results became extremely high again, with recall@1=0.2955, recall@5=0.6121 and recall@10=0.7324.

Therefore we wonder if you have any idea about this abnormal result, maybe because of the data_process part? 

Thank you!

**Comment by currybur** [comment]
This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla. 

Thanks to the author Sun Ke for providing us with much helpful information!

**Comment by flyz1** [comment]
> This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla.
> 
> Thanks to the author Sun Ke for providing us with much helpful information!

hello，would you mind sharing foursquare dataset that the author used in this code？I'm sorry I can't find the dataset. Thank you very much!

**Comment by FFFantine** [comment]
> This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla.
> 
> Thanks to the author Sun Ke for providing us with much helpful information!

Hello, thanks a lot for your discussion.

I have the same problem when I deal with the Gowalla dataset. Would you mind sharing the correct processed method of the Gowalla dataset to match the correct result of this paper? Thank you very much!

**Comment by currybur** [comment]
> > This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla.
> > Thanks to the author Sun Ke for providing us with much helpful information!
> 
> Hello, thanks a lot for your discussion.
> 
> I have the same problem when I deal with the Gowalla dataset. Would you mind sharing the correct processed method of the Gowalla dataset to match the correct result of this paper? Thank you very much!

Hi there. According to the author, they processed Gowalla following this paper [TMCA](https://github.com/zhenql/TMCA). They also provided us with a 90MB Gowalla file which I suppose to be greatly cropped, put it [here](https://drive.google.com/file/d/1r4yXRdXXC9NDdcNCHUUP4E9cUONzOXWT/view?usp=sharing). By the way, their foursquare is from [SERM](https://github.com/yaodi833/serm).

Hope this will be helpful to you.

**Comment by FFFantine** [comment]
> > > This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla.
> > > Thanks to the author Sun Ke for providing us with much helpful information!
> > 
> > 
> > Hello, thanks a lot for your discussion.
> > I have the same problem when I deal with the Gowalla dataset. Would you mind sharing the correct processed method of the Gowalla dataset to match the correct result of this paper? Thank you very much!
> 
> Hi there. According to the author, they processed Gowalla following this paper [TMCA](https://github.com/zhenql/TMCA). They also provided us with a 90MB Gowalla file which I suppose to be greatly cropped, put it [here](https://drive.google.com/file/d/1r4yXRdXXC9NDdcNCHUUP4E9cUONzOXWT/view?usp=sharing). By the way, their foursquare is from [SERM](https://github.com/yaodi833/serm).
> 
> Hope this will be helpful to you.

Thanks very much for your help^^

**Comment by Athenallu** [comment]
> > > This should be a result of the variant in data set, both different version of foursquare and different processed Gowalla.
> > > Thanks to the author Sun Ke for providing us with much helpful information!
> > 
> > 
> > Hello, thanks a lot for your discussion.
> > I have the same problem when I deal with the Gowalla dataset. Would you mind sharing the correct processed method of the Gowalla dataset to match the correct result of this paper? Thank you very much!
> 
> Hi there. According to the author, they processed Gowalla following this paper [TMCA](https://github.com/zhenql/TMCA). They also provided us with a 90MB Gowalla file which I suppose to be greatly cropped, put it [here](https://drive.google.com/file/d/1r4yXRdXXC9NDdcNCHUUP4E9cUONzOXWT/view?usp=sharing). By the way, their foursquare is from [SERM](https://github.com/yaodi833/serm).
> 
> Hope this will be helpful to you.

你好，我用你发的链接中的foursquare数据集运行代码，但是出现了这个问题：ValueError: not enough values to unpack (expected 10, got 9)，我是把原tweets-cikm.txt文件当成本项目中的tweet_clean_all.txt文件来用的，请问是哪里有问题吗？非常感谢！
